create database project2026;
use project2026;

select * from `food(1)`;
select * from `menu(1)`;
select * from `orders(1) (1)`;
select * from `restaurant(1)`;
select * from `users(1)`;

#1. List all users from a specific city
select * from `users(1)` where city = 'kochi';

#2. Display all orders with status **'Delivered'**.
select * from `orders(1) (1)` where order_status = 'delivered';

#3. Find the **10 most expensive food items**.
select * from `food(1)` order by price desc limit 10;

#4. List all vegetarian food items.
select * from `food(1)`where veg = 'yes';

#5. Find restaurants with a rating of **4.5 or higher**.
select * from `restaurant(1)` where rating >= 4.5;

#6. Display all orders paid using **UPI**.
select * from `orders(1) (1)` where payment_method = 'upi';

#7. List all available menu items.
select * from `menu(1)` where availability = 'available';

#8. Find all orders placed in **August 2026**.
select * from `orders(1) (1)` where order_date between '2026-08-01' and '2026-08-31';

#9. Find the **10 restaurants with the longest delivery time**.
select * from `restaurant(1)` order by delivery_time_min desc limit 10;

#10. List orders where the total amount is **greater than ₹1,000**, sorted by amount in descending order.
select * from `orders(1) (1)` where total_amount > 1000 order by total_amount desc;

#11. Find all users who signed up in 2025.
select * from `users(1)`where year(signup_date) = 2025;

#12. Find all food items with a price less than ₹200.
select * from `food(1)`where price < 200;

#13. Display all restaurants located in Kochi.
select * from `restaurant(1)`where city = 'kochi';

#14. Find all orders where the quantity is greater than 2.
select * from `orders(1) (1)`where quantity > 2;

#15. Display the 5 highest-rated restaurants, sorted by rating from highest to lowest.
select * from `restaurant(1)`order by rating desc limit 5;

----------------------------------------------------------------------

#1. What is the **total revenue** generated from all orders? 
select sum(total_amount) as total_revenue
from `orders(1) (1)`;

#2.  How many orders did each restaurant receive? 
select restaurant_id, count(order_id) as total_orders
from `orders(1) (1)`
group by restaurant_id
order by total_orders desc;

#3.  Find the **top 5 users by total spending**. 
select user_id, sum(total_amount) as total_spending
from `orders(1) (1)`
group by user_id
order by total_spending desc
limit 5;

#4.  Calculate the total revenue generated by each restaurant. 
select restaurant_id, sum(total_amount) as total_revenue
from `orders(1) (1)`
group by restaurant_id
order by total_revenue desc;

#5.  Which food category sold the **highest number of units**? 
select f.category, sum(o.quantity) as total_units
from `food(1)` f
join `orders(1) (1)` o
on f.food_id = o.food_id
group by f.category
order by total_units desc
limit 1;

#6.  For each payment method, find the number of orders, total amount, and average order value. 
select payment_method,
       count(order_id) as total_orders,
       sum(total_amount) as total_amount,
       avg(total_amount) as average_order_value
from `orders(1) (1)`
group by payment_method;

#7.  Find restaurants that generated **more than ₹5,000 revenue**.
select restaurant_id,
sum(total_amount) as total_revenue
from `orders(1) (1)`
group by restaurant_id
having sum(total_amount) > 5000
order by total_revenue desc; 

#8.  Display each restaurant's name, rating, order count, and total revenue.
select r.restaurant_name,r.rating,
count(o.order_id) as order_count,
sum(o.total_amount) as total_revenue
from `restaurant(1)`r
join `orders(1) (1)` o
on r.restaurant_id = o.restaurant_id
group by r.restaurant_id, r.restaurant_name, r.rating
order by total_revenue desc;
 
#9.  Calculate the **total revenue for each month of 2026**. 
select month(order_date) as month,
sum(total_amount) as total_revenue
from `orders(1) (1)`
where year(order_date) = 2026
group by month(order_date)
order by month;

-------------------------------------------------------------------------

#1.Identify repeat customers who placed more than 2 orders.
select user_id,
       count(order_id) as total_orders
from `orders(1) (1)`
group by user_id
having count(order_id) > 2;


#2.Use a CTE to calculate monthly orders, revenue, and average order value.
with monthly_sales as (
    select month(order_date) as month,
           count(order_id) as total_orders,
           sum(total_amount) as total_revenue,
           avg(total_amount) as average_order_value
    from `orders(1) (1)`
    where year(order_date) = 2026
    group by month(order_date)
)
select *
from monthly_sales
order by month;

#3.Find restaurants whose revenue is greater than the average restaurant revenue.
select restaurant_id,
       total_revenue
from (
    select restaurant_id,
           sum(total_amount) as total_revenue
    from `orders(1) (1)`
    group by restaurant_id
) as restaurant_revenue
where total_revenue > (
    select avg(total_revenue)
    from (
        select restaurant_id,
               sum(total_amount) as total_revenue
        from `orders(1) (1)`
        group by restaurant_id
    ) as average_revenue
);


#4.Create a view named monthly_sales_summary containing monthly orders, revenue, and average order value.
create view monthly_sales_summary as
select month(order_date) as month,
       count(order_id) as total_orders,
       sum(total_amount) as total_revenue,
       avg(total_amount) as average_order_value
from `orders(1) (1)`
where year(order_date) = 2026
group by month(order_date);

select * from monthly_sales_summary;

#4.Create a stored procedure get_customer_history(user_id) to return a user's complete order
delimiter //
create procedure get_customer_history(in p_user_id int)
begin
    select o.order_id,
           o.order_date,
           r.restaurant_name,
           f.food_name,
           o.quantity,
           o.total_amount,
           o.order_status
    from `orders(1) (1)` o
    join `restaurant(1)` r
    on o.restaurant_id = r.restaurant_id
    join `food(1)` f
    on o.food_id = f.food_id
    where o.user_id = p_user_id
    order by o.order_date desc;
end //
delimiter ;
call get_customer_history(1);

#5.Rank restaurants based on their total revenue using a window function.
select restaurant_id,
       total_revenue,
       rank() over(order by total_revenue desc) as revenue_rank
from (
    select restaurant_id,
           sum(total_amount) as total_revenue
    from `orders(1) (1)`
    group by restaurant_id
) as restaurant_revenue;